[package]
name = "filehasher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.6"
rust-crypto = "0.2.36"
walkdir = "2.3.2"
